### Login and save token
# @no-cookie-jar
POST {{baseUrl}}/htmx/auth/login
Content-Type: application/x-www-form-urlencoded
HX-Request: true

email={{username}}&password={{password}}

> {%
    const setCookieHeader = response.headers.valueOf("Set-Cookie");
    if (setCookieHeader) {
        const tokenMatch = setCookieHeader.match(/token=([^;]+)/);
        if (tokenMatch) {
            client.global.set("token", tokenMatch[1]);
        }
    }
%}